#---------------------------------------------------------------------
# Tools
#---------------------------------------------------------------------
[tools]
"aqua:coreos/butane" = "latest"

#---------------------------------------------------------------------
# Tasks
#---------------------------------------------------------------------
[tasks.test]
description = "Run unattended installation test"
usage = '''
flag "-d --device <device>" help="Device configuration to validate" default="buran"
flag "-v --version <version>" help="Fedora release version" default="44"
'''
run = [
  "tests/launch.sh {{ usage.device }} {{ usage.version }}",
  "rm -rf .cache/{{ usage.device }}"
]

[tasks."ignition:transpile"]
description = "Transpile source Butane Config into an Ignition Config file"
usage = '''
arg "<source>" help="Path to source Butane Config file"
arg "<target>" help="Path where to store transpiled Ignition Config file"
'''
run = "butane --pretty --strict {{ usage.source }} > {{ usage.target }}"

[tasks.clean]
description = "Clean up all cached files"
run = "rm -rf .cache"