#---------------------------------------------------------------------
# Tools
#---------------------------------------------------------------------
[tools]
"aqua:coreos/butane" = "latest"

#---------------------------------------------------------------------
# Variables
#---------------------------------------------------------------------
[vars]
fedora_version = 44

#---------------------------------------------------------------------
# Tasks
#---------------------------------------------------------------------
[tasks."tests:foton"]
description = "Run unattended installation test for 'foton' device"
run = [
  "tests/launch.sh --device foton --iso tests/fedora-{{ vars.fedora_version }}.iso --kickstart laptops/foton/fedora-{{ vars.fedora_version }}.ks",
  "rm -rf .cache/foton"
]

[tasks."tests:buran"]
description = "Run unattended installation test for 'buran' device"
run = [
  "tests/launch.sh --device buran --iso tests/fedora-{{ vars.fedora_version }}.iso --kickstart desktops/buran/fedora-{{ vars.fedora_version }}.ks",
  "rm -rf .cache/buran"
]

[tasks."ignition:transpile"]
description = "Transpile source Butane Config into an Ignition Config file"
usage = '''
arg "<source>" help="Path to source Butane Config file"
arg "<target>" help="Path where to store transpiled Ignition Config file"
'''
run = "butane --pretty --strict {{ usage.source }} > {{ usage.target }}"

[tasks.cleanup]
description = "Clean up all cached files"
run = "rm -rf .cache"