# - Installation options -
text
eula --accept
firstboot --disabled
reboot --eject

# - Lang and keyboard -
lang en_US.UTF-8
keyboard fr

# - Timezone -
timezone Europe/Paris

# - SELinux -
selinux --enforcing

# - Network -
network --onboot=yes --bootproto="dhcp" --hostname="buran"

# - Firewall -
firewall --enabled

# - Storage -
clearpart --drives=nvme0n1 --all
partition /boot/efi --ondisk=nvme0n1 --fstype=vfat --size=512
partition /boot     --ondisk=nvme0n1 --fstype=ext4 --size=1024 
partition /         --ondisk=nvme0n1 --fstype=ext4 --grow --encrypted --passphrase="<redacted>"
partition /mnt/S1   --onpart="UUID=d2481502-4bcd-42ec-b3b2-4e4fa14bd708" --label="S1" --fsoptions="noatime,x-gvfs-show" --noformat
partition /mnt/S2   --onpart="UUID=f9717af5-a7ee-4721-8295-73283704a9c3" --label="S2" --fsoptions="noatime,x-gvfs-show" --noformat

# - Graphics -
xconfig --startxonboot

# - Users and groups -
rootpw --lock
user --name=fbobin --gecos="Florian Bobin" --groups="docker,gamemode,systemd-journal,wheel" --shell="/usr/bin/zsh" --password="<redacted>" --plaintext

# - Authentication -
authselect select local with-pam-u2f with-pam-u2f-2fa with-mdns4

# - Kernel options -
# preempt=full - Fully preemptive kernel for better desktop reponsiveness and latency in gaming
# split_lock_detect=off - https://github.com/CachyOS/linux-cachyos/issues/555
# nowatchdog - Disable all kernel watchdogs
bootloader --append="preempt=full split_lock_detect=off nowatchdog"

# - Repositories -
repo --name=updates
repo --name=fedora-cisco-openh264 --metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-cisco-openh264-$releasever&arch=$basearch
repo --name=rpmfusion-free --metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch
repo --name=rpmfusion-free-updates --metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$basearch --cost=0
repo --name=rpmfusion-nonfree --metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-$releasever&arch=$basearch
repo --name=rpmfusion-nonfree-updates --metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-$releasever&arch=$basearch --cost=0

# - Packages -
%packages
@fonts
@gnome-desktop
@hardware-support
@multimedia
@networkmanager-submodules
@printing
@workstation-product

bind-utils
cascadia-fonts-all
chezmoi
distrobox
docker-buildx
docker-compose
duf
fastfetch
fd-find
fzf
gamemode
gamescope
gawk
gnome-extensions-app
gnome-tweaks
gnome-shell-extension-appindicator
gnome-shell-extension-dash-to-dock
helm
httpie
jq
k9s
kind
kubernetes-client
libva-utils
lm_sensors
mangohud
moby-engine
mycli
netcat
nmap
ntsync-autoload
nvme-cli
nvtop
pamu2fcfg
pgcli
pipx
ripgrep
rpmfusion-free-release
rpmfusion-nonfree-release
rsync
s3cmd
skopeo
socat
steam
strace
systemd-container
tcpdump
tio
tree
vim-enhanced
wget2-wget
wireguard-tools
yamllint
yaru-theme
yq
zoxide
zram-generator-defaults
zsh
zstd

-abrt*
-decibels
-gnome-boxes
-gnome-characters
-gnome-contacts
-gnome-font-viewer
-gnome-maps
-gnome-system-monitor
-gnome-tour
-gnome-weather
-malcontent-control
-mediawriter
-libreoffice*
-rhythmbox
-sssd*
-showtime
-toolbox
-unoconv
-yelp
%end

# - Services -
services --enabled=docker.socket --disabled=docker.service,flatpak-add-fedora-repos.service

# - Post Installation -
%post --erroronfail --logfile=/var/log/anaconda/post-installation.log --interpreter=/usr/bin/bash

# Third-party packages
tee /etc/yum.repos.d/brave-browser.repo > /dev/null << 'EOF'
[brave-browser]
name=Brave Browser
baseurl=https://brave-browser-rpm-release.s3.brave.com/$basearch
enabled=1
gpgcheck=1
gpgkey=https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
EOF

tee /etc/yum.repos.d/vscode.repo > /dev/null << 'EOF'
[vscode]
name=Visual Studio Code
baseurl=https://packages.microsoft.com/yumrepos/vscode
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
EOF

dnf install -y brave-browser code

# Flatpaks
FLATPAK_APPS=(
    "be.alexandervanhee.gradia"
    "com.bitwarden.desktop"
    "com.discordapp.Discord"
    "com.github.tchx84.Flatseal"
    "com.heroicgameslauncher.hgl"
    "com.vysp3r.ProtonPlus"
    "de.haeckerfelix.Fragments"
    "io.bassi.Amberol"
    "io.github.ilya_zlobintsev.LACT"
    "me.iepure.devtoolbox"
    "net.nokyan.Resources"
    "org.jeffvli.feishin"
    "org.musicbrainz.Picard"
    "org.nicotine_plus.Nicotine"
    "org.videolan.VLC"
)
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install -y flathub "${FLATPAK_APPS[@]}"

# Kernel modules and drivers
tee /etc/modprobe.d/blacklist-amd-watchdog.conf > /dev/null << 'EOF'
# Generated by Kickstart
blacklist sp5100_tco
EOF

tee /etc/modprobe.d/amdgpu-overdrive.conf > /dev/null << 'EOF'
# Generated by Kickstart
options amdgpu ppfeaturemask=0xffffffff
EOF

dracut --regenerate-all --force

# GRUB
grub2-editenv - set menu_auto_hide=1

# sysctl
tee /etc/sysctl.d/90-zram.conf > /dev/null << 'EOF'
# Generated by Kickstart
# https://wiki.archlinux.org/title/Zram#Optimizing_swap_on_zram
vm.swappiness=180
vm.page-cluster=0
vm.watermark_boost_factor=0
vm.watermark_scale_factor=125
EOF

# auditd
sed -ie 's|^write_logs =.*|write_logs = no|' /etc/audit/auditd.conf

# systemd-journald
tee /etc/systemd/journald.conf > /dev/null << 'EOF'
# Generated by Kickstart
[Journal]
Storage=persistent
Compress=yes
SystemMaxFileSize=256M
RuntimeMaxUse=100M
EOF

# GDM
tee /etc/tmpfiles.d/10-gdm-monitors-settings.conf > /dev/null << 'EOF'
# Generated by Kickstart
# Applies current desktop scaling value to GDM to avoid it being 'too zoomed-in'
r /etc/xdg/monitors.xml
C /etc/xdg/monitors.xml 0644 root root - /home/fbobin/.config/monitors.xml
EOF

# sudo
tee /etc/sudoers.d/00-defaults > /dev/null << 'EOF'
# Generated by Kickstart
Defaults insults
Defaults lecture=never
Defaults passwd_timeout=1
EOF

# DNF
tee /etc/dnf/dnf.conf > /dev/null << 'EOF'
# Generated by Kickstart
[main]
max_parallel_downloads=10
defaultyes=True
EOF

# Bluetooth
tee /etc/bluetooth/main.conf > /dev/null << 'EOF'
# Generated by Kickstart
[Policy]
AutoEnable=false
EOF

# Docker
mkdir -p /etc/docker
tee /etc/docker/daemon.json > /dev/null << 'EOF'
{
  "cgroup-parent": "docker.slice",
  "features": {
    "buildkit": true,
    "cdi": true,
    "containerd-snapshotter": true
  },
  "iptables": true,
  "live-restore": true,
  "log-driver": "local",
  "max-concurrent-downloads": 5,
  "max-concurrent-uploads": 5,
  "userland-proxy": false
}
EOF

# SELinux
setsebool -P container_manage_cgroup true

# Wrappers
tee /usr/local/bin/bw > /dev/null << 'EOF'
#!/usr/sbin/sh
exec flatpak run --command=bw com.bitwarden.desktop "$@"
EOF
chmod +x /usr/local/bin/bw

tee /usr/local/bin/brave-launcher > /dev/null << 'EOF'
#!/usr/bin/env bash
set -euo pipefail
BRAVE_FLAGS_FILE="${HOME}/.config/brave-flags.conf"
USER_FLAGS=()
if [[ -f "${BRAVE_FLAGS_FILE}" ]]; then
  mapfile -t USER_FLAGS < "${BRAVE_FLAGS_FILE}"
fi
exec /usr/bin/brave-browser "$@" "${USER_FLAGS[@]-}"
EOF
chmod +x /usr/local/bin/brave-launcher
%end