# - Installer options -
text
eula --accept
firstboot --disabled
reboot --eject

# - Lang and keyboard -
lang en_US.UTF-8
keyboard fr

# - Timezone -
timezone Europe/Paris

# - SELinux -
selinux --enforcing

# - Network -
network --onboot=yes --bootproto="dhcp" --hostname="foton"

# - Firewall -
firewall --enabled

# - Storage -
clearpart --drives=nvme0n1 --all
partition /boot/efi --ondisk=nvme0n1 --fstype=vfat --size=512
partition /boot     --ondisk=nvme0n1 --fstype=ext4 --size=1024 
partition /         --ondisk=nvme0n1 --fstype=ext4 --grow --encrypted --passphrase="dev"

# - Graphics -
xconfig --startxonboot

# - Users and groups -
rootpw --lock
user --name=fbobin --gecos="Florian Bobin" --groups="docker,systemd-journal,wheel" --shell="/usr/bin/zsh" --password="dev" --plaintext

# - Authentication -
authselect select local with-fingerprint with-pam-u2f with-pam-u2f-2fa with-mdns4

# - Kernel options -
# preempt=full - Fully preemptive kernel for better desktop reponsiveness
# nowatchdog - Disable all kernel watchdogs
# i915.force_probe=!7d55 xe.force_probe=7d55 xe.enable_psr=0 - Force Xe driver and disable Panel Self Refresh (PSR)
bootloader --append="preempt=full nowatchdog i915.force_probe=!7d55 xe.force_probe=7d55 xe.enable_psr=0"

# - Repositories -
repo --name=updates
repo --name=fedora-cisco-openh264 --metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-cisco-openh264-$releasever&arch=$basearch
repo --name=rpmfusion-free --metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch
repo --name=rpmfusion-free-updates --metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$basearch --cost=0
repo --name=rpmfusion-nonfree --metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-$releasever&arch=$basearch
repo --name=rpmfusion-nonfree-updates --metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-$releasever&arch=$basearch --cost=0

# - Packages -
%packages
@firefox
@fonts
@gnome-desktop
@hardware-support
@multimedia
@networkmanager-submodules
@printing
@workstation-product

bind-utils
cascadia-fonts-all
chezmoi
distrobox
docker-buildx
docker-compose
duf
fastfetch
fd-find
fdk-aac
fprintd-pam
fzf
gawk
genisoimage
gnome-extensions-app
gnome-tweaks
gnome-shell-extension-appindicator
gnome-shell-extension-dash-to-dock
gparted
helm
httpie
igt-gpu-tools
intel-media-driver
jq
k9s
kernel-modules-extra
kubernetes-client
libva-intel-media-driver
libva-utils
lm_sensors
moby-engine
mycli
nmap
nmap-ncat
nvme-cli
pamu2fcfg
pgcli
powertop
qemu-img
qemu-kvm-core
ripgrep
rpmfusion-free-release
rpmfusion-nonfree-release
rsync
rtl-sdr
s3cmd
seahorse
skopeo
socat
strace
systemd-container
tcpdump
tio
tree
uv
vim-enhanced
wget2-wget
wireguard-tools
yamllint
yaru-theme
yq
zoxide
zram-generator-defaults
zsh
zstd

-abrt*
-decibels
-gnome-boxes
-gnome-characters
-gnome-contacts
-gnome-font-viewer
-gnome-maps
-gnome-system-monitor
-gnome-tour
-gnome-weather
-malcontent-control
-mediawriter
-libreoffice*
-rhythmbox
-sssd*
-showtime
-toolbox
-unoconv
-yelp
%end

# - Services -
services --enabled=docker.socket
services --disabled=auditd.service,docker.service,flatpak-add-fedora-repos.service

# - Post Installation -
%post --erroronfail --logfile=/var/log/anaconda/post-installation.log --interpreter=/usr/bin/bash

# Third-party packages
tee /etc/yum.repos.d/vscode.repo << 'EOF'
[vscode]
name=Visual Studio Code
baseurl=https://packages.microsoft.com/yumrepos/vscode
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
EOF
dnf install -y code

# Flatpaks
FLATPAK_APPS=(
    "be.alexandervanhee.gradia"
    "com.bitwarden.desktop"
    "com.discordapp.Discord"
    "com.github.tchx84.Flatseal"
    "com.usebottles.bottles"
    "me.iepure.devtoolbox"
    "net.nokyan.Resources"
    "org.gnome.Fractal"
    "org.jeffvli.feishin"
    "org.musicbrainz.Picard"
    "org.nicotine_plus.Nicotine"
    "org.videolan.VLC"
)
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install -y flathub "${FLATPAK_APPS[@]}"

# Kernel modules and drivers
tee /etc/modprobe.d/blacklist-rtl28xxu.conf << 'EOF'
# Generated by Kickstart
# Blacklist RTL28xx drivers to avoid conflict with Osmocom RTL-SDR drivers
blacklist dvb_usb_rtl28xxu
EOF

# GRUB
grub2-editenv - set menu_auto_hide=1

# sysctl
tee /etc/sysctl.d/90-zram.conf << 'EOF'
# Generated by Kickstart
# https://wiki.archlinux.org/title/Zram#Optimizing_swap_on_zram
vm.swappiness=180
vm.page-cluster=0
vm.watermark_boost_factor=0
vm.watermark_scale_factor=125
EOF

# systemd-journald
tee /etc/systemd/journald.conf > /dev/null << 'EOF'
# Generated by Kickstart
[Journal]
Storage=persistent
Compress=yes
SystemMaxFileSize=256M
RuntimeMaxUse=100M
EOF

# GDM
tee /etc/tmpfiles.d/10-gdm-monitors-settings.conf << 'EOF'
# Generated by Kickstart
# Applies current desktop scaling value to GDM to avoid it being 'too zoomed-in'
r /etc/xdg/monitors.xml
C /etc/xdg/monitors.xml 0644 root root - /home/fbobin/.config/monitors.xml
EOF

# sudo
tee /etc/sudoers.d/00-defaults << 'EOF'
# Generated by Kickstart
Defaults insults
Defaults lecture=never
Defaults passwd_timeout=1
EOF

# DNF
tee /etc/dnf/dnf.conf << 'EOF'
# Generated by Kickstart
[main]
max_parallel_downloads=10
defaultyes=True
EOF

# Bluetooth
tee /etc/bluetooth/main.conf << 'EOF'
# Generated by Kickstart
[Policy]
AutoEnable=false
EOF

# Docker
mkdir -p /etc/docker
tee /etc/docker/daemon.json << 'EOF'
{
  "cgroup-parent": "docker.slice",
  "iptables": true,
  "live-restore": true,
  "log-driver": "local",
  "max-concurrent-downloads": 5,
  "max-concurrent-uploads": 5,
  "userland-proxy": false
}
EOF
setsebool -P container_manage_cgroup true

# Wrappers
tee /usr/local/bin/bw > /dev/null << 'EOF'
#!/usr/sbin/sh
exec flatpak run --command=bw com.bitwarden.desktop "$@"
EOF
chmod +x /usr/local/bin/bw
%end